### ISSUE TITLE
Having trouble starting

### ISSUE THREAD

**Issue by phtmgt** [bellbind/docker-ruby18-rails2#1]
Hey there,

New to docker here and probably this is a stupid question. Anyways,

docker run -it --rm -v $(pwd)/my-rails-app:/root/app -w /root/app -p 3000:3000  bellbind/docker-ruby18-rails2 ruby script/server

gets me 

ruby: No such file or directory -- script/server (LoadError)

script/server definitely exists in /root/app. Maybe I'm doing something else wrong.

**Comment by p11v** [comment]
And, I answered it myself. I am quite a newbie, apparently. I thought that we could use existing code outside the container (thought /root/app was path to the existing code). Apparently not.
